appname = energy-service
httpport = 8082
runmode = dev
autorender = false
copyrequestbody = true

database.driver = mysql
database.datasource = spuser:sp123456@tcp(127.0.0.1:3306)/smartplant_ems?charset=utf8mb4&parseTime=True&loc=Local

session.on = false

log.level = debug
log.path = logs/
