appname = device-service
httpport = 8081
runmode = dev
autorender = false
copyrequestbody = true

database:
  driver = mysql
  datasource = spuser:sp123456@tcp(sp_mysql:3306)/smartplant_ems?charset=utf8mb4&parseTime=True&loc=Local

session:
  on = false

log:
  level = debug
  path = logs/